version: 2.1

orbs:
  node: circleci/node@4.1
  aws-s3: circleci/aws-s3@2.0

workflows:
  sample:
    jobs:
      - node/test:
          version: "15.1"
          # after the node/test job completes, build the dist packages and save them to a workspace
          post-steps:
            - run: npm run build
            - aws-s3/copy:
                from: dist/
                to: s3://sample-app-vue
                arguments: --recursive